Sprint_2
Perevotortov/qa_python pull request #2
Opened 2023-07-15 18:27 UTC by Perevotortov

Привет!
В пул-реквест включены 4 файла: 1) gitignore (по теме Git создал его, и в него добавил python файлы) , 2) файл с кодом main, код в гитхабе и код в тренажере отличались поэтому я вставил в main код из тренажера , 3) файл tests с кодом тестов , 4) файл conftest, в который вписал 3 фикстуры и проверки для их работы.
Постарался подписать многострочным комментарием каждый тест отдельно. При переносе из своего черновика в проект, файл conftest начал ругаться на import pytest, я сам не понял в чем проблема. Локально все запускалось (проверил раз 5 мб), но именно в проекте ругается. Уже поздновато чтобы спрашивать в куратора, поэтому отправляю так, если нужно будет это исправить - исправлю.
Буду ждать просмотра, если нужны будут дополнительные комментарии то постараюсь их дать по возможности максимально быстро.

2023-07-16 09:00 UTC, kadirovgm requested changes

2023-07-16 10:49 UTC, Perevotortov commented
Привет! Спасибо за комментарии, сейчас напишу что исправил.
1) Исправил комменты для фикстур в докстринг формат

2) Нужно исправить test_get_books_for_children_get_books_for_kids. 
Исправил, добавил параметризацию с двумя книгами. Строки 44-49.

3) Нужно исправить в файле conftest. В моем понимании эти два теста
относятся только к проверкам фикстур - я проверяю что они 
работают правильно. Это не является проверкой кода задания, 
так что прошу рассматривать проверки только класса "TestBooksCollector".
Проверки TestFixtures только для понимания что правильно работает фикстура, 
наверное следует их вообще вырезать, но пока перенес их просто в основной
файл - tests и закомментил. 

4) Нужно исправить test_add_book_in_favorites_add_book_to_favorites.
Я не использовал другой метод, т к в случае если он не будет работать,
то эта проверка упадет (пытался разделить функционал добавления в фавориты
и получения списка фаворитов). Но если надо, то заменил 
books_collector.favorites на books_collector.get_list_of_favorites_book().

Честно говоря, хотел бы уточнить этот вопрос:
Метод  get_list_of_favorites_book() в теле содержит "return self.favorites"
Насколько я понял(могу ошибаться) это то же самое что 
books_collector.favorites, но в варианте который отправлял изначально
опущен момент с обращением к методу, а вызываю список напрямую.
Можешь пожалуйста написать в ответе на пул реквест - правильны ли мои рассуждения
по поводу того что стоит стараться пропускать зависимости тестов 
от других методов, или лучше обращаться через методы вместо прямого вызова
списка фаворитов в данном случае?

5) Нужно исправить test_delete_book_from_favorites_delete_from_favorites.
Аналогичная ситуация пункту 4. Исправил с books_collector.favorites  на 
books_collector.get_list_of_favorites_book().
Вот ссылка на коммит "Переделка номер 1" - https://github.com/Perevotortov/qa_python/pull/2/commits/1d56ae3358426ac6b6f77a0e1f13a67aa82de564

2023-07-17 18:56 UTC, kadirovgm commented
Привет! конечно же books_collector.favorites и get_list_of_favorites_book() это одно и то же, но так как мы пишем тесты для этих методов, то в тестах стоит пользоваться именно тестируемыми методами, пусть и проверка другого функционала. Таким образом мы просто повышаем покрытие тестами.

2023-07-17 18:58 UTC, kadirovgm approved these changes

2023-08-07 12:12 UTC, merged